### PR TITLE
Fixed new compile issue #6 (wrong artifact for sbt.io)

### PR DESCRIPTION
**Pull request by phderome**
…Moved RateLimiter.scala (without any CircuitBreaker mind you) back to… Chapter12 as per book

Fixed sbt.IO dependency/artifact in build.scala and chapter13 (must have been in .ivy cache for rkuhn), removed some unused imports
directory change for MultiMasterCRDTSpec.scala (now chapter13)

Note: keep in mind that **this code may well diverge** from the zip on Manning's website.

### CODE REVIEW

**Comment by rkuhn** [comment]
It seems that my click on “update branch” did not trigger the clahub check, could you rebase on current master and force-push? That should get things going—and then you’ll have to sign the Apache 2 CLA to keep the lawyers happy (sorry about that; the link should pop up after the expected check failure).

**Comment by phderome** [comment]
I may do before Easter, i.e. shortly, on vacation coming week.

**Comment by phderome** [comment]
I did a sync of upstream/master (the official repo Roland maintains) to my forked branch. Not sure what I can do here, now. Maybe a new fresh PR?

**Comment by rkuhn** [comment]
Hmm, not sure what got stuck here and how to get it unstuck. Thanks for the mailed CLA, to keep records in one place would you mind [signing electronically](https://www.clahub.com/agreements/ReactiveDesignPatterns/CodeSamples)?

**Comment by phderome** [comment]
I signed, not sure if you did anything to fix, but whatever it is done. I will be back in a week.

**Pull request merged**
